name: Deploy

on:
  push:
    branches:
      - deploy-react-app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client # Specify the client directory

      # Step 4: Build the project
      - name: Build project
        run: npm run build
        working-directory: client # Specify the client directory

      # Step 5: Upload the production build files
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./client/dist # Path to the build output

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 6: Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist